..\bin\bp -q5 [brev] tell('bm.txt') call(big) call(told) call(halt)
..\bin\bp -q5 [cal] tell_at_end('bm.txt') go(100000) call(told) call(halt)
..\bin\bp -q5 -h8000 -t1000 [boyer] tell_at_end('bm.txt') call(go) call(told) call(halt)
..\bin\bp -q5 -h7000 [tsp] tell_at_end('bm.txt') call(go) call(told) call(halt)
..\bin\bp -q5 -h3000 [tak] tell_at_end('bm.txt') call(go) call(told) call(halt)
..\bin\bp -q5 -h20000 -t2000 -b0 [allperms] tell_at_end('bm.txt') call(go) call(told) call(halt)
..\bin\bp -q5 [bfmeta] tell_at_end('bm.txt') call(go) call(told) call(halt)
..\bin\bp -q5 -h20000 -t2000 [gc] tell_at_end('bm.txt') call(go) call(told) call(halt)
..\bin\bp -q5 -h2000 -s16000 [choice] tell_at_end('bm.txt') call(go) call(told) call(halt)
..\bin\bp -q5 [war] tell_at_end('bm.txt') call(go) call(told) call(halt)
..\bin\bp -q5 -h2000 [chat] tell_at_end('bm.txt') call(go) call(told) call(halt)
